djcrm/urls.py
from django.contrib import admin
from django.urls import path,include
from leads.views import LandingPageView,SignUpView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (LoginView,
                            LogoutView,
                            PasswordResetView,
                            PasswordResetConfirmView,
                            PasswordResetDoneView,
                            PasswordResetCompleteView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(),name='landing-page'),
    path('leads/',include('leads.urls',namespace='leads')),
    path('agents/',include('agents.urls',namespace='agents')),
    path('signup/',SignUpView.as_view(),name='signup'),
    path('login/',LoginView.as_view(),name='login'),
    path('reset-password/',PasswordResetView.as_view(),name='reset-password'),
    path('password-reset-done/',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('logout/',LogoutView.as_view(),name='logout')
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name='leads'

urlpatterns = [
    path('',views.LeadListView.as_view(),name='lead-list'),
    path('create/',views.LeadCreateView.as_view(),name='lead-create'),
    path('<int:pk>/',views.LeadDetailView.as_view(),name='lead-detail'),
    path('<int:pk>/assign-agent/',views.AssignAgentView.as_view(),name='assign-agent'),
    path('<int:pk>/lead-category/',views.LeadCategoryUpdateView.as_view(),name='lead-category'),
    path('<int:pk>/update/',views.LeadUpdateView.as_view(),name='lead-update'),
    path('<int:pk>/delete/',views.LeadDeleteView.as_view(),name='lead-delete'),
    path('categories/',views.CategoryListView.as_view(),name='category-list'),
    path('categories/<int:pk>/',views.CategoryDetailView.as_view(),name='category-detail'),
    path('categories/<int:pk>/update/',views.CategoryUpdateView.as_view(),name='category-update'),
    path('categories/<int:pk>/delete/',views.CategoryDeleteView.as_view(),name='category-delete'),
    path('create-category/',views.CategoryCreateView.as_view(),name='create-category'),
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
# Create your models here.

class User(AbstractUser):
    is_organisor=models.BooleanField(default=True)
    is_agent=models.BooleanField(default=False)

class UserProfile(models.Model):
   user=models.OneToOneField(User,on_delete=models.CASCADE)

   def __str__(self):
       return self.user.username 

#These are the fields of the model, which store the data for each Lead instance 
# # The first_name and last_name fields are strings that store the name of the Lead 
# # The age field is an integer that stores the age of the Lead, with a default value of 0 
# # The agent field is a foreign key to the Agent model, which means that each Lead belongs to one Agent, and an Agent can have many Leads 
# # The on_delete argument specifies what happens when the related Agent is deleted. In this case, it uses models.CASCADE, which means that if the Agent is deleted, the Lead will also be deleted
class Lead(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    age=models.IntegerField(default=0)
    organisation=models.ForeignKey(UserProfile,related_name='leads',on_delete=models.CASCADE)
    agent=models.ForeignKey('Agent',related_name='leads',on_delete=models.SET_NULL,null=True,blank=True)
    category=models.ForeignKey('Category',related_name='leads',on_delete=models.SET_NULL,blank=True,null=True)
    description=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    phone_number=models.CharField(max_length=20)
    email=models.EmailField()

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"


# These are the fields of the model, which store the data for each Agent instance 
# # The user field is a one-to-one relationship with the User model, which means that each Agent can have only one User, and vice versa 
# # The organisation field is a foreign key to the UserProfile model, which means that each Agent belongs to one UserProfile, but a UserProfile can have many Agents 
# # The on_delete argument specifies what happens when the related User or UserProfile is deleted. In this case, it uses models.CASCADE, which means that if the User or UserProfile is deleted, the Agent will also be deleted
class Agent(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    organisation=models.ForeignKey(UserProfile,related_name='agents',on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.email
    

class Category(models.Model):
    name=models.CharField(max_length=100)
    organisation=models.ForeignKey(UserProfile,related_name='categories',on_delete=models.CASCADE,blank=True,null=True)

    def __str__(self) -> str:
        return self.name


def post_user_created_signal(sender,instance,created,**kwargs):
   if created:
       UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal,sender=User)

leads/forms.py
from django import forms
from .models import Lead,User,Agent,Category
from django.contrib.auth.forms import UserCreationForm,UsernameField

class LeadForm(forms.ModelForm):
   class Meta:
      model=Lead
      fields=('first_name',
              'last_name',
              'age',
              'agent',
              'description',
              'phone_number',
              'email')

class CustomUserCreationForm(UserCreationForm):
   class Meta:
      model=User
      fields = ("username",)
      field_classes = {"username": UsernameField}

class AssignAgentForm(forms.Form):
   agent=forms.ModelChoiceField(queryset=Agent.objects.none())

   def __init__(self,*args,**kwargs):
      request=kwargs.pop('request')
      agents=Agent.objects.filter(organisation=request.user.userprofile)
      super(AssignAgentForm,self).__init__(*args,**kwargs)
      self.fields['agent'].queryset=agents

class LeadCategoryUpdateForm(forms.ModelForm):
   class Meta:
      model=Lead
      fields=('category',)

class CategoryForm(forms.ModelForm):
   class Meta:
      model=Category
      fields=('name',)

leads/views.py
from typing import Any
from django.core.mail import send_mail
from django.db import models
from .models import Lead,Agent,Category
from django.urls import reverse,reverse_lazy
from .forms import LeadForm,CustomUserCreationForm,AssignAgentForm,LeadCategoryUpdateForm,CategoryForm
from django.contrib.auth import login,authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from agents.mixins import OrganisorAndLoginRequiredMixin
# Create your views here.

class SignUpView(generic.CreateView):
    form_class=CustomUserCreationForm
    template_name='registration/signup.html'

    def form_valid(self, form):
        response=super().form_valid(form)
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1']
        )
        login(self.request,user)
        return response
    
    def get_success_url(self) -> str:
        return reverse('leads:lead-list')


class LandingPageView(generic.TemplateView):
    template_name='landing-page.html'


class LeadListView(LoginRequiredMixin,generic.ListView):
    model=Lead
    template_name="leads/lead_list.html"
    context_object_name="leads"

    def get_queryset(self):
        user=self.request.user
        if user.is_organisor:
            queryset=Lead.objects.filter(organisation=user.userprofile,agent__isnull=False)
        else:
            queryset=Lead.objects.filter(organisation=user.agent.organisation,agent__isnull=False)
            queryset=queryset.filter(agent__user=user)
        return queryset
    
    def get_context_data(self, **kwargs):
        context=super(LeadListView,self).get_context_data(**kwargs)
        user=self.request.user
        if user.is_organisor:
            queryset=Lead.objects.filter(organisation=user.userprofile)
            context.update({
                 'unassigned_leads':queryset.filter(agent__isnull=True)
                })
        return context



class LeadDetailView(LoginRequiredMixin,generic.DetailView):
    model=Lead
    template_name="leads/lead_detail.html"

    def get_queryset(self):
        user=self.request.user
        if user.is_organisor:
            queryset=Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset=Lead.objects.filter(organisation=user.agent.organisation)
            queryset=queryset.filter(agent__user=user)
        return queryset

class LeadCreateView(OrganisorAndLoginRequiredMixin,generic.CreateView):
    model=Lead
    template_name='leads/lead_create.html'
    success_url=reverse_lazy('leads:lead-list')
    form_class=LeadForm

    def form_valid(self,form) :
        lead=form.save(commit=False)
        lead.organisation=self.request.user.userprofile
        lead.save()
        #send notification to agent mail
        return super(LeadCreateView,self).form_valid(form)
    
class AssignAgentView(OrganisorAndLoginRequiredMixin,generic.FormView):
    template_name='leads/assign_agent.html'
    form_class=AssignAgentForm
    success_url=reverse_lazy('leads:lead-list')

    def get_form_kwargs(self,**kwargs):
        kwargs=super(AssignAgentView,self).get_form_kwargs(**kwargs)
        kwargs.update({
            'request':self.request
        })
        return kwargs
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        return context
    
    def form_valid(self, form):
        lead=Lead.objects.get(pk=self.kwargs['pk'])
        lead.agent=form.cleaned_data.get('agent')
        lead.save()
        return super(AssignAgentView,self).form_valid(form)

class LeadUpdateView(OrganisorAndLoginRequiredMixin,generic.UpdateView):
    model=Lead
    template_name='leads/lead_update.html'
    success_url=reverse_lazy('leads:lead-list')
    form_class=LeadForm

    def get_queryset(self):
        user=self.request.user
        return Lead.objects.filter(organisation=user.userprofile)
    


# def lead_update(request,pk):
#     lead=Lead.objects.get(pk=pk)
#     form=LeadForm(instance=lead)
#     if request.method=='POST':
#         #pass a lead data in here otherwise it'd create a new entry
#         form=LeadForm(request.POST,instance=lead)
#         if form.is_valid():
#             form.save()
#             return redirect(f'/leads')
#     return render(request,'leads/lead_update.html',{"form":form,"lead":lead})

class LeadDeleteView(OrganisorAndLoginRequiredMixin,generic.DeleteView):
    template_name='leads/lead_delete.html'
    model=Lead
    success_url=reverse_lazy('leads:lead-list')
    
    def get_queryset(self):
        user=self.request.user
        return Lead.objects.filter(organisation=user.userprofile)

class CategoryListView(LoginRequiredMixin,generic.ListView):
    template_name='leads/category_list.html'
    model=Category
    context_object_name='categories'

    def get_context_data(self, **kwargs):
        context=super(CategoryListView,self).get_context_data(**kwargs)
        user=self.request.user
        if user.is_organisor:
            queryset=Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset=Lead.objects.filter(organisation=user.agent.organisation)
        context.update({
            'unassigned_leads':queryset.filter(category__isnull=True).count(),
        })
        return context

    def get_queryset(self):
        user=self.request.user
        if user.is_organisor:
            queryset=Category.objects.filter(organisation=user.userprofile)
        else:
            queryset=Category.objects.filter(organisation=user.agent.organisation)
        return queryset
    
class CategoryDetailView(LoginRequiredMixin,generic.DetailView):
    template_name='leads/category_detail.html'
    model=Category
    context_object_name='category'

    def get_queryset(self):
        user=self.request.user
        if user.is_organisor:
            queryset=Category.objects.filter(organisation=user.userprofile)
        else:
            queryset=Category.objects.filter(organisation=user.agent.organisation)
        return queryset
    
class CategoryCreateView(OrganisorAndLoginRequiredMixin,generic.CreateView):
    template_name='leads/category_create.html'
    model=Category
    form_class=CategoryForm

    def get_success_url(self) -> str:
        return reverse('leads:category-list')
    
    def form_valid(self,form) :
        category=form.save(commit=False)
        category.organisation=self.request.user.userprofile
        category.save()
        #send notification to agent mail
        return super(CategoryCreateView,self).form_valid(form)

class CategoryUpdateView(OrganisorAndLoginRequiredMixin,generic.UpdateView):
    template_name='leads/category_update.html'
    model=Category
    form_class=CategoryForm

    def get_success_url(self) -> str:
        return reverse('leads:category-list')
    
    def get_queryset(self):
        user=self.request.user
        if user.is_organisor:
            queryset=Category.objects.filter(organisation=user.userprofile)
        else:
            queryset=Category.objects.filter(organisation=user.agent.organisation)
        return queryset

class CategoryDeleteView(OrganisorAndLoginRequiredMixin,generic.DeleteView):
    template_name="leads/category_delete.html"
    model=Category
    
    def get_success_url(self) -> str:
        return reverse('leads:category-list')
    
    def get_queryset(self):
        user=self.request.user
        if user.is_organisor:
            queryset=Category.objects.filter(organisation=user.userprofile)
        else:
            queryset=Category.objects.filter(organisation=user.agent.organisation)
        return queryset


class LeadCategoryUpdateView(LoginRequiredMixin,generic.UpdateView):
    template_name='leads/lead_category_update.html'
    model=Lead
    form_class=LeadCategoryUpdateForm

    def get_success_url(self) -> str:
        return reverse('leads:lead-detail',kwargs={'pk':self.get_object().id})
    
    def get_queryset(self):
        user=self.request.user
        if user.is_organisor:
            queryset=Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset=Lead.objects.filter(organisation=user.agent.organisation)
            queryset=queryset.filter(agent__user=user)
        return queryset

leads/templates/leads/category_detail.html
{% extends 'base.html' %}
{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{category.name}}</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These are the leads under this category</p>
        <a class="hover:text-blue-500" href="{% url 'leads:category-update' category.pk %}">Update</a>
        <a class="hover:text-blue-500" href="{% url 'leads:category-delete' category.pk %}">Delete</a>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">First Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Last Name</th>
            </tr>
          </thead>
          <tbody>
            {% for lead in category.leads.all %}
            <tr>
              <td class="px-4 py-3">{{lead.first_name}}</td>
              <td class="px-4 py-3">{{lead.last_name}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

{% endblock content %}

leads/templates/leads/category_list.html
{% extends 'base.html' %}
{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These categories seggregate the leads</p>
        <a href="{% url 'leads:create-category' %}" class="hover:text-blue-500">Create a new category</a>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead count</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="px-4 py-3">Unassigned Leads</td>
              <td class="px-4 py-3">{{unassigned_leads}}</td>
            </tr>
            {% for category in categories %}
            <tr>
              <td class="px-4 py-3"><a class="hover:text-violet-500" href="{% url 'leads:category-detail' category.pk %}">{{category.name}}</a></td>
              <td class="px-4 py-3">{{category.leads.all.count}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      
    </div>
  </section>

{% endblock content %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Leads</h1>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:category-list' %}">
                    View categories
                </a>
            </div>
            {% if request.user.is_organisor %}
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:lead-create' %}">
                    Create a new lead
                </a>
            </div>
            {% endif %}
        </div>

        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            First Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Last Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Age
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Email
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Cell Phone Number
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Category
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                            <span class="sr-only">Edit</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for lead in leads %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <a class="text-blue-500 hover:text-blue-800" href="{% url 'leads:lead-detail' lead.pk %}">{{ lead.first_name }}</a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.last_name }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.age }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.email }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.phone_number }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {% if lead.category %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                            {{ lead.category.name }}
                                        </span>
                                    {% else %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
                                            Unassigned
                                        </span>
                                    {% endif %}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="{% url 'leads:lead-update' lead.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                        Edit
                                    </a>
                                </td>
                            </tr>

                        {% empty %}

                        <p>There are currently no leads</p>

                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
  
        {% if unassigned_leads.exists %}
            <div class="mt-5 flex flex-wrap -m-4">
                <div class="p-4 w-full">
                    <h1 class="text-4xl text-gray-800">Unassigned leads</h1>
                </div>
                {% for lead in unassigned_leads %}
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>
                        </div>
                        <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                {{ lead.first_name }} {{ lead.last_name }}
                            </h2>
                            <p class="leading-relaxed text-base">
                                {{ lead.description }}
                            </p>
                            <a href="{% url 'leads:assign-agent' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                                Assign an agent
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</section>
{% endblock content %}











{% comment %} {% extends 'base.html' %} {% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div
      class="w-full mb-6 py-6 flex justify-between items-center border-gray-200"
    >
      <div>
        <h1 class="text-4xl text-gray-700">Leads</h1>
        <a
          class="text-gray-500 hover:text-violet-500"
          href="{% url 'leads:category-list' %}"
          >View Categories</a
        >
      </div>
      {% if request.user.is_organisor %}
      <div>
        <a
          class="text-gray-500 hover:text-violet-500"
          href="{% url 'leads:lead-create' %}"
          >Create a new lead</a
        >
      </div>
      {% endif %}
    </div>
    <div class="flex flex-wrap -m-4">
      {% for lead in leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div
          class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col"
        >
          <div
            class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0"
          >
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-10 h-10"
              viewBox="0 0 24 24"
            >
              <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{lead.first_name}} {{lead.last_name}}
            </h2>
            <p class="leading-relaxed text-base">
              {{lead.description}}
            </p>
            <a
              href="{% url 'leads:lead-detail' lead.id %}"
              class="mt-3 text-indigo-500 inline-flex items-center"
              >view this lead
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
              >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% if unassigned_leads.exists %}
    <div class="mt-5 flex flex-wrap -m-4">
      <div class="w-full p-5">
        <h1 class="text-4xl text-gray-700">Unassigned Leads</h1>
      </div>
      {% for lead in unassigned_leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div
          class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col"
        >
          <div
            class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0"
          >
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-10 h-10"
              viewBox="0 0 24 24"
            >
              <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{lead.first_name}} {{lead.last_name}}
            </h2>
            <p class="leading-relaxed text-base">
              {{lead.description}}
            </p>
            <a
              href="{% url 'leads:assign-agent' lead.id %}"
              class="mt-3 text-indigo-500 inline-flex items-center"
              >assign an agent 
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
              >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %} {% endif %}
    </div>
  </div>
</section>
{% endblock content %} {% endcomment %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead-detail' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
          <a href="{% url 'leads:lead-category' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
          <a href="{% url 'leads:lead-update' lead.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update Details</a>
        </div>
        <form action="." method="post">
          {% csrf_token %}
          {{form|crispy}}
          <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md" type="submit">update</button>
        </form>
        <div class="mt-5 border-t border-gray-200">
          <a href="{% url 'leads:lead-delete' lead.id %}"  class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete</a>
        </div>  
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>  
{% endblock content %}