agents/urls.py
from django.urls import path
from .views import (AgentListView,
                    AgentCreateView,AgentDetailView,AgentUpdateView,AgentDeleteView)
app_name='agents'

urlpatterns = [
    path('',AgentListView.as_view(),name='agent-list'),
    path('create/',AgentCreateView.as_view(),name='agent-create'),
    path('<int:pk>/',AgentDetailView.as_view(),name='agent-detail'),
    path('<int:pk>/update/',AgentUpdateView.as_view(),name='agent-update'),
    path('<int:pk>/delete/',AgentDeleteView.as_view(),name='agent-delete'),
]

djcrm/urls.py
from django.contrib import admin
from django.urls import path,include
from leads.views import LandingPageView,SignUpView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (LoginView,
                            LogoutView,
                            PasswordResetView,
                            PasswordResetConfirmView,
                            PasswordResetDoneView,
                            PasswordResetCompleteView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(),name='landing-page'),
    path('leads/',include('leads.urls',namespace='leads')),
    path('agents/',include('agents.urls',namespace='agents')),
    path('signup/',SignUpView.as_view(),name='signup'),
    path('login/',LoginView.as_view(),name='login'),
    path('reset-password/',PasswordResetView.as_view(),name='reset-password'),
    path('password-reset-done/',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('logout/',LogoutView.as_view(),name='logout')
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name='leads'

urlpatterns = [
    path('',views.LeadListView.as_view(),name='lead-list'),
    path('create/',views.LeadCreateView.as_view(),name='lead-create'),
    path('<int:pk>/',views.LeadDetailView.as_view(),name='lead-detail'),
    path('<int:pk>/assign-agent/',views.AssignAgentView.as_view(),name='assign-agent'),
    path('<int:pk>/lead-category/',views.LeadCategoryUpdateView.as_view(),name='lead-category'),
    path('<int:pk>/update/',views.LeadUpdateView.as_view(),name='lead-update'),
    path('<int:pk>/delete/',views.LeadDeleteView.as_view(),name='lead-delete'),
    path('categories/',views.CategoryListView.as_view(),name='category-list'),
    path('categories/<int:pk>/',views.CategoryDetailView.as_view(),name='category-detail'),
    path('categories/<int:pk>/update/',views.CategoryUpdateView.as_view(),name='category-update'),
    path('categories/<int:pk>/delete/',views.CategoryDeleteView.as_view(),name='category-delete'),
    path('create-category/',views.CategoryCreateView.as_view(),name='create-category'),
]

templates/includes/navbar.html
<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl"><a href="{% url 'landing-page' %}">DJ CRM</a></span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        {% if not request.user.is_authenticated %}
        <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Sign Up</a>
        {% else %}
        {% if request.user.is_organisor %}
        <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900">Agents</a>
        {% endif %}
        <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>
        {% endif %}
      </nav>
      {% if request.user.is_authenticated %}
      you are logged in as: {{request.user.username}}
      <a href="{% url 'logout' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
        Log Out
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
     {% else %}
      <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
        Log In
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
      {% endif %}
    </div>
  </header>