agents/urls.py
from django.urls import path
from .views import (AgentListView,
                    AgentCreateView,AgentDetailView,AgentUpdateView,AgentDeleteView)
app_name='agents'

urlpatterns = [
    path('',AgentListView.as_view(),name='agent-list'),
    path('create/',AgentCreateView.as_view(),name='agent-create'),
    path('<int:pk>/',AgentDetailView.as_view(),name='agent-detail'),
    path('<int:pk>/update/',AgentUpdateView.as_view(),name='agent-update'),
    path('<int:pk>/delete/',AgentDeleteView.as_view(),name='agent-delete'),
]

djcrm/urls.py
from django.contrib import admin
from django.urls import path,include
from leads.views import LandingPageView,SignUpView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (LoginView,
                            LogoutView,
                            PasswordResetView,
                            PasswordResetConfirmView,
                            PasswordResetDoneView,
                            PasswordResetCompleteView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(),name='landing-page'),
    path('leads/',include('leads.urls',namespace='leads')),
    path('agents/',include('agents.urls',namespace='agents')),
    path('signup/',SignUpView.as_view(),name='signup'),
    path('login/',LoginView.as_view(),name='login'),
    path('reset-password/',PasswordResetView.as_view(),name='reset-password'),
    path('password-reset-done/',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('logout/',LogoutView.as_view(),name='logout')
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
User=get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('email','username','first_name','last_name')

agents/views.py
from django.views import generic
from leads.models import Agent,User
from django.urls import reverse_lazy
from django.core.mail import send_mail
from .forms import AgentModelForm
from .mixins import OrganisorAndLoginRequiredMixin
# Create your views here.

class AgentListView(OrganisorAndLoginRequiredMixin,generic.ListView):
    template_name='agents/agent_list.html'
    model=Agent
    context_object_name='agents'

    def get_queryset(self):
       organisation=self.request.user.userprofile
       return Agent.objects.filter(organisation=organisation)

class AgentCreateView(OrganisorAndLoginRequiredMixin,generic.CreateView):
    template_name='agents/agent_create.html'
    form_class=AgentModelForm
    success_url=reverse_lazy('agents:agent-list')

    def form_valid(self, form):
        user=form.save(commit=False)
        user.is_organisor=False
        user.is_agent=True
        user.set_password('testahg')
        user.save()
        Agent.objects.create(user=user,organisation=self.request.user.userprofile)
        send_mail(subject='you are invited as an agent',message='you were added as an agent on DJCRM. Please come and login and start working',
                  recipient_list=[user.email],from_email='DJCRM@adminUser.com')
        return super(AgentCreateView,self).form_valid(form)


class AgentDetailView(OrganisorAndLoginRequiredMixin,generic.DetailView):
    model=Agent
    template_name='agents/agent_detail.html'
    
    def get_queryset(self):
       organisation=self.request.user.userprofile
       return Agent.objects.filter(organisation=organisation)
    
class AgentUpdateView(OrganisorAndLoginRequiredMixin,generic.UpdateView):
    template_name='agents/agent_update.html'
    success_url=reverse_lazy('agents:agent-list')
    form_class=AgentModelForm
    model=User

    def get_queryset(self):
    #    organisation=self.request.user.userprofile
    #    return Agent.objects.filter(organisation=organisation)
       return User.objects.all()

class AgentDeleteView(OrganisorAndLoginRequiredMixin,generic.DeleteView):
    model=Agent
    success_url=reverse_lazy('agents:agent-list')
    template_name='agents/agent_delete.html'
    
    def get_queryset(self):
       organisation=self.request.user.userprofile
       return Agent.objects.filter(organisation=organisation)

agents/templates/agents/agent_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<div class="max-w-lg mx-auto">
  <div class="py-5 border-b border-gray-200">
    <a class="hover:text-blue-500" href="{% url 'agents:agent-list' %}">Go back to agents list</a>
  </div>
  <h1 class="mt-5 text-4xl text-gray-800">Create a Agent here</h1>
  <form action="." method="post" class="mt-5">
    {% csrf_token %}
    {{form|crispy}}
    <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md" type='submit'>Submit</button>
  </form>
</div>
{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<div class="max-w-lg mx-auto">
  <div class="py-5 mt-5 border-b border-gray-200">
    <a class="hover:text-violet-500 mt-3" href="{% url 'agents:agent-list' %}">Go back to the agents</a>
  </div>
  <h1 class="text-4xl text-grey-800 my-5">are you sure want to delete this Agent?</h1>
  <form action="." method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button class="w-full text-white bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md" type='submit'>Delete</button>
  </form>  
</div>
{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'agents:agent-detail' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'agents:agent-update' agent.user.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Update Details
                </a>    
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Full Name</span>
                <span class="ml-auto text-gray-900">{{ agent.user.first_name }} {{ agent.user.last_name }}</span>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Email</span>
                <span class="ml-auto text-gray-900">{{ agent.user.email }}</span>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}



{% comment %} {% extends 'base.html' %}
{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}}</h1>
          <div class="flex mb-4">
            <a href="{% url 'agents:agent-detail' agent.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
            <a href="{% url 'agents:agent-update' agent.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Details</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900"></span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Location</span>
            <span class="ml-auto text-gray-900">Seattle, Washington</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Cell Number</span>
            <span class="ml-auto text-gray-900">+122598337</span>
          </div>
          <div class="flex">
            <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
            <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
              </svg>
            </button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>
{% endblock content %} {% endcomment %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-700 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
                <div>
                    <h1 class="text-4xl text-gray-800">Agents</h1>
                </div>
                <div>
                    <a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent-create' %}">Create a new agent</a>
                </div>
            </div>

            <div class="flex flex-col w-full">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Full Name
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Email
                                </th>
                                <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Edit</span>
                                </th>
                                <th scope="col" class="relative px-6 py-3">
                                  <span class="sr-only">Details</span>
                                  </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for agent in agents %}
                                <tr class="bg-white">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {{ agent.user.first_name }} {{ agent.user.last_name }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ agent.user.email }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{% url 'agents:agent-update' agent.user.id %}" class="text-indigo-600 hover:text-indigo-900">
                                            Edit
                                        </a>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-rigth text-sm font-medium">
                                      <a href="{% url 'agents:agent-detail' agent.pk%}" class="text-indigo-600 hover:text-indigo-900">
                                        Details
                                      </a>
                                    </td>
                                </tr>
                            {% empty %}

                            <p>There are currently no agents</p>

                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
                </div>
            </div>

        </div>
      </section>
{% endblock content %}


{% comment %} {% extends 'base.html' %}
{% block content %}
    <section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-gray-200">
        <div>
            <h1 class="text-4xl text-gray-700">Agents</h1>
        </div>
        <div>
            <a class="text-gray-500 hover:text-violet-500" href="{% url 'agents:agent-create' %}">Create a new Agent</a>
        </div>
    </div>
    <hr>
    <div class="flex flex-wrap -m-4">
    {% for agent in agents%}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
              <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{agent.user.username}}</h2>
            <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a href="{% url 'agents:agent-detail' agent.id %}" class="mt-3 text-indigo-500 inline-flex items-center">view this agent
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %} {% endcomment %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ user.username }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'agents:agent-detail' user.agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'agents:agent-update' user.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'agents:agent-delete' user.agent.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}